### ISSUE TITLE
Synthesizing HyperBus

### ISSUE THREAD

**Issue by chensy7** [pulp-platform/hyperbus#13]
Hello! Thanks for open sourcing. I'm trying to synthesize the HyperBus 2.0 interface to get a sense of the size of the module (with Cadence Genus). However, I'm running into a lot of errors during synthesis. I see that some of the other PULP modules are used in the SV files. Is there a place where I can learn how to set up the modules required to synthesize HyperBus? Thanks!

**Comment by FrancescoConti** [comment]
You might want to take a look at Carfield https://github.com/pulp-platform/carfield/ https://pulp-platform.github.io/carfield/um/arch/ for a recent SoC integrating the HyperBus.

**Comment by chensy7** [comment]
Thanks!
